name: medi_eccomerce_flutter_getx
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logos/

  fonts:
    - family: Aeroport
      fonts:
        - asset: assets/fonts/Aeroport/Aeroport.ttf
        - asset: assets/fonts/Aeroport/Aeroport-Bold.ttf
        - asset: assets/fonts/Aeroport/Aeroport-BoldItalic.ttf
        - asset: assets/fonts/Aeroport/Aeroport-Italic.ttf
    - family: Barlow
      fonts:
        - asset: assets/fonts/Barlow/Barlow-Black.ttf
        - asset: assets/fonts/Barlow/Barlow-Bold.ttf
        - asset: assets/fonts/Barlow/Barlow-Italic.ttf